SELECT * FROM app_configINSERT INTO session (
    id,
    init_date,
    init_time,
    end_date,
    end_time,
    station_id,
    app_user_id,
    period_type,
    cash_init,
    cash_final,
    credit_cards_final,
    check_final,
    ticket_final,
    term_final,
    finances_final,
    cash_init2,
    cash_final2,
    credit_cards_final2,
    check_final2,
    ticket_final2,
    term_final2,
    finances_final2,
    finished,
    reviewed,
    custom_payment_method_final
  )
VALUES (
    id:int,
    'init_date:date',
    'init_time:time',
    'end_date:date',
    'end_time:time',
    station_id:int,
    app_user_id:int,
    period_type:int,
    cash_init:int,
    cash_final:int,
    'credit_cards_final:varchar',
    check_final:int,
    ticket_final:int,
    term_final:int,
    'finances_final:varchar',
    cash_init2:int,
    cash_final2:int,
    'credit_cards_final2:varchar',
    check_final2:int,
    ticket_final2:int,
    term_final2:int,
    'finances_final2:varchar',
    'finished:tinyint',
    'reviewed:tinyint',
    'custom_payment_method_final:varchar'
  );



